"""add branch_inn, tax_office_code, customs_refs

Revision ID: 9ea18ef4e591
Revises: cf15352b4898
Create Date: 2026-06-27 10:30:20.708201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ea18ef4e591'
down_revision: Union[str, None] = 'cf15352b4898'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('esf_items', sa.Column('customs_refs', sa.String(length=255), nullable=True))
    op.add_column('esf_parties', sa.Column('branch_inn', sa.String(length=20), nullable=True))
    op.add_column('esf_parties', sa.Column('tax_office_code', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('esf_parties', 'tax_office_code')
    op.drop_column('esf_parties', 'branch_inn')
    op.drop_column('esf_items', 'customs_refs')
    # ### end Alembic commands ###
