"""add esf_documents.issue_date

Revision ID: a21036a5126a
Revises: 9ea18ef4e591
Create Date: 2026-06-27 11:18:27.565523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a21036a5126a'
down_revision: Union[str, None] = '9ea18ef4e591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('esf_documents', sa.Column('issue_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('esf_documents', 'issue_date')
    # ### end Alembic commands ###
