"""esf_baseline_schema

Revision ID: cf15352b4898
Revises: 
Create Date: 2026-06-26 18:27:58.008516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf15352b4898'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('inn', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_inn'), 'organizations', ['inn'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('esf_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'VALIDATED', 'SNAPSHOT_CREATED', 'PUBLISHED', 'CANCELLED', name='document_status'), server_default='DRAFT', nullable=False),
    sa.Column('esf_number', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('qr_path', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_esf_documents_esf_number'), 'esf_documents', ['esf_number'], unique=True)
    op.create_index(op.f('ix_esf_documents_organization_id'), 'esf_documents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_esf_documents_owner_id'), 'esf_documents', ['owner_id'], unique=False)
    op.create_index(op.f('ix_esf_documents_status'), 'esf_documents', ['status'], unique=False)
    op.create_index(op.f('ix_esf_documents_uuid'), 'esf_documents', ['uuid'], unique=True)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('meta_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['esf_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_document_id'), 'audit_logs', ['document_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('esf_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(length=100), nullable=True),
    sa.Column('tnved_code', sa.String(length=50), nullable=True),
    sa.Column('product_name', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Numeric(precision=20, scale=5), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=20, scale=5), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('vat_rate', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('vat_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('nsp', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['esf_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'row_number', name='uq_item_document_row')
    )
    op.create_index(op.f('ix_esf_items_document_id'), 'esf_items', ['document_id'], unique=False)
    op.create_table('esf_parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('party_type', sa.Enum('SUPPLIER', 'BUYER', name='party_type'), nullable=False),
    sa.Column('inn', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('branch', sa.String(length=500), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('tax_office', sa.String(length=255), nullable=True),
    sa.Column('bank', sa.String(length=255), nullable=True),
    sa.Column('bik', sa.String(length=20), nullable=True),
    sa.Column('account', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['esf_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'party_type', name='uq_party_document_type')
    )
    op.create_index(op.f('ix_esf_parties_document_id'), 'esf_parties', ['document_id'], unique=False)
    op.create_table('esf_signatures',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('director_name', sa.String(length=255), nullable=True),
    sa.Column('signature_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['esf_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_table('esf_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('immutable', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['esf_documents.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_esf_snapshots_document_id'), 'esf_snapshots', ['document_id'], unique=False)
    op.create_index(op.f('ix_esf_snapshots_sha256'), 'esf_snapshots', ['sha256'], unique=False)
    op.create_index(op.f('ix_esf_snapshots_uuid'), 'esf_snapshots', ['uuid'], unique=True)
    op.create_table('esf_supply_info',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('supply_date', sa.Date(), nullable=True),
    sa.Column('supply_type', sa.String(length=100), nullable=True),
    sa.Column('payment_type', sa.String(length=100), nullable=True),
    sa.Column('contract_number', sa.String(length=100), nullable=True),
    sa.Column('contract_date', sa.Date(), nullable=True),
    sa.Column('correction_flag', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('correction_reason', sa.Text(), nullable=True),
    sa.Column('currency_code', sa.String(length=10), nullable=True),
    sa.Column('currency_rate', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['esf_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_table('esf_totals',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('vat_total', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('nsp_total', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('grand_total', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('currency_total', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['esf_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('esf_totals')
    op.drop_table('esf_supply_info')
    op.drop_index(op.f('ix_esf_snapshots_uuid'), table_name='esf_snapshots')
    op.drop_index(op.f('ix_esf_snapshots_sha256'), table_name='esf_snapshots')
    op.drop_index(op.f('ix_esf_snapshots_document_id'), table_name='esf_snapshots')
    op.drop_table('esf_snapshots')
    op.drop_table('esf_signatures')
    op.drop_index(op.f('ix_esf_parties_document_id'), table_name='esf_parties')
    op.drop_table('esf_parties')
    op.drop_index(op.f('ix_esf_items_document_id'), table_name='esf_items')
    op.drop_table('esf_items')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_document_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_esf_documents_uuid'), table_name='esf_documents')
    op.drop_index(op.f('ix_esf_documents_status'), table_name='esf_documents')
    op.drop_index(op.f('ix_esf_documents_owner_id'), table_name='esf_documents')
    op.drop_index(op.f('ix_esf_documents_organization_id'), table_name='esf_documents')
    op.drop_index(op.f('ix_esf_documents_esf_number'), table_name='esf_documents')
    op.drop_table('esf_documents')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_index(op.f('ix_organizations_inn'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
    # Drop the enum types implicitly created by the tables above so that a
    # downgrade -> upgrade cycle does not fail with "type already exists".
    sa.Enum(name='party_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='document_status').drop(op.get_bind(), checkfirst=True)
