"""add counterparties table

Revision ID: d2389f930148
Revises: a21036a5126a
Create Date: 2026-06-27 16:22:17.567400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2389f930148'
down_revision: Union[str, None] = 'a21036a5126a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counterparties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inn', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('branch', sa.String(length=500), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('tax_office', sa.String(length=255), nullable=True),
    sa.Column('bank', sa.String(length=255), nullable=True),
    sa.Column('bik', sa.String(length=20), nullable=True),
    sa.Column('account', sa.String(length=50), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_counterparties_inn'), 'counterparties', ['inn'], unique=True)
    op.create_index(op.f('ix_counterparties_name'), 'counterparties', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_counterparties_name'), table_name='counterparties')
    op.drop_index(op.f('ix_counterparties_inn'), table_name='counterparties')
    op.drop_table('counterparties')
    # ### end Alembic commands ###
